In [1]:
#!pip install alpaca_trade_api

In [2]:
import alpaca_trade_api as tradeapi
import pandas as pd
import datetime

In [3]:
api = tradeapi.REST()
start_date = '2019-01-01T00:00:00-23:59'
end_date = '2019-12-31T00:00:00-23:59'

# Get daily price data for FACEBOOK for 2019.
barset = api.get_barset('FB', 'day', start = start_date, end = end_date)
fb_bars = barset['FB']

# Get daily price data for AMAZON for 2019.
barset = api.get_barset('AMZN', 'day', start = start_date, end = end_date)
amzn_bars = barset['AMZN']

# Get daily price data for APPLE for 2019.
barset = api.get_barset('AAPL', 'day', start = start_date, end = end_date)
aapl_bars = barset['AAPL']

# Get daily price data for NETFLIX for 2019.
barset = api.get_barset('NFLX', 'day', start = start_date, end = end_date)
nflx_bars = barset['NFLX']

# Get daily price data for GOOGLE for 2019.
barset = api.get_barset('GOOGL', 'day', start = start_date, end = end_date)
googl_bars = barset['GOOGL']

In [4]:
# Create FACEBOOK's data list from fb_bars 
fb_list = []
for i in range(len(fb_bars)):
    fb_list.append([fb_bars[i].t,
                 fb_bars[i].o,
                 fb_bars[i].h,
                 fb_bars[i].l,
                 fb_bars[i].c,
                 fb_bars[i].v])
    
# Create AMAZON's data list from amzn_bars
amzn_list = []
for i in range(len(amzn_bars)):
    amzn_list.append([amzn_bars[i].t,
                 amzn_bars[i].o,
                 amzn_bars[i].h,
                 amzn_bars[i].l,
                 amzn_bars[i].c,
                 amzn_bars[i].v])

# Create APPLE's data list from aapl_bars
aapl_list = []
for i in range(len(aapl_bars)):
    aapl_list.append([aapl_bars[i].t,
                 aapl_bars[i].o,
                 aapl_bars[i].h,
                 aapl_bars[i].l,
                 aapl_bars[i].c,
                 aapl_bars[i].v])

# Create NETFLIX's data list from nflx_bars
nflx_list = []
for i in range(len(nflx_bars)):
    nflx_list.append([nflx_bars[i].t,
                 nflx_bars[i].o,
                 nflx_bars[i].h,
                 nflx_bars[i].l,
                 nflx_bars[i].c,
                 nflx_bars[i].v])

# Create GOOGLE's data list from googl_bars
googl_list = []
for i in range(len(googl_bars)):
    googl_list.append([googl_bars[i].t,
                 googl_bars[i].o,
                 googl_bars[i].h,
                 googl_bars[i].l,
                 googl_bars[i].c,
                 googl_bars[i].v])

In [11]:

#Creating DataFrames from Lists
fb_df = pd.DataFrame(fb_list)
amzn_df = pd.DataFrame(amzn_list)
aapl_df = pd.DataFrame(aapl_list)
nflx_df = pd.DataFrame(nflx_list)
googl_df = pd.DataFrame(googl_list)

cols = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
fb_df.columns=(cols)
amzn_df.columns=(cols)
aapl_df.columns=(cols)
nflx_df.columns=(cols)
googl_df.columns=(cols)

fb_df['Date'] = pd.to_datetime(fb_df.Date).dt.date
amzn_df['Date'] = pd.to_datetime(amzn_df.Date).dt.date
aapl_df['Date'] = pd.to_datetime(aapl_df.Date).dt.date
nflx_df['Date'] = pd.to_datetime(nflx_df.Date).dt.date
googl_df['Date'] = pd.to_datetime(googl_df.Date).dt.date

In [12]:
googl_df.head()

         Date     Open     High        Low     Close   Volume
0  2019-01-02  1027.20  1060.79  1025.2750  1053.240  1346501
1  2019-01-03  1050.67  1066.26  1022.3700  1026.505  1546910
2  2019-01-04  1041.63  1080.00  1036.8600  1076.550  1792417
3  2019-01-07  1080.97  1082.70  1062.6400  1076.010  1872050
4  2019-01-08  1084.77  1093.35  1068.3486  1085.510  1402631

In [13]:

#Saving data to .csv files
fb_df.to_csv("../Resources/fb_data.csv", encoding='utf-8', index = False)
amzn_df.to_csv("../Resources/amzn_data.csv", encoding='utf-8', index = False)
aapl_df.to_csv("../Resources/aapl_data.csv", encoding='utf-8', index = False)
nflx_df.to_csv("../Resources/nflx_data.csv", encoding='utf-8', index = False)
googl_df.to_csv("../Resources/googl_data.csv", encoding='utf-8', index = False)